# copy this file to "api.config.yml" and modify as needed for your local dev environment

APP_ENV: dev # dev|prod
POSTGRES_USER: solo-platform
POSTGRES_PASS: solo-platform-db-password
POSTGRES_DB: solo-platform
POSTGRES_HOST: postgres:5432
APP_PUBLIC_UPLOADS_BASEURL: http://localhost:5000/_public
APP_FS_TYPE: local # local|gcs
APP_FS_OS_PATH: static/uploads
APP_FS_GCS_URL: ~
JWT_SECRET: this-is-not-secret