# copy this file to "api.config.yml" and modify as needed for your local dev environment

APP_ENV: dev # dev|prod
POSTGRES_USER: solo-platform
POSTGRES_PASS: solo-platform-db-password
POSTGRES_DB: solo-platform
POSTGRES_HOST: postgres:5432
APP_PUBLIC_UPLOADS_BASEURL: http://localhost:3000/_public
APP_FS_TYPE: local # local|gcs
APP_FS_OS_PATH: static/uploads
APP_FS_GCS_URL: ~
JWT_SECRET: this-is-not-secret
JWT_ISSUER: solo.api.com
TOKBOX_APIKEY: 46003062
TOKBOX_SECRET: 688ecb8f0804f57db0781aa829896a0b3301c9fa
REDIS_URL: redis:6379

# Note that these are URLs inteded for a browser, not for backend communication between docker services
WEBAPP_URL: http://localhost:3003
WEBAPP_URL_CONFIRM_EMAIL: http://localhost:3003/email/verify
WEBAPP_URL_RESET_PASSWORD: http://localhost:3003/password/reset

EMAIL_ENABLED: false
EMAIL_FROM_ADDRESS: no-reply@example.com
EMAIL_USER: user@example.com
EMAIL_PASS: user-email-password
EMAIL_PORT: "587"
EMAIL_DOMAIN: smtp.example.com
