version: '2'

services:
  # run ad hoc commands
  solo-api: 
    image: gcr.io/solo-infrastructure/solo-platform-api:0.46.4
    volumes:
      - ./.gcp/app-key.json:/app/gcp/app-key.json
      - ./api.config.yml:/app/config/config.yml

  # run the api server w/ docs
  solo-api-server:
    extends: solo-api
    restart: always
    command: ["api-server"]
    ports:
      - ${SOLOAPI_PORT}:80
  
  # run the web app
  solo-web-app:
    image: gcr.io/solo-infrastructure/solo-web-app:0.2.0
    restart: always
    ports:
      - 3003:80
    environment:
      API_URL: http://localhost:${SOLOAPI_PORT}

  # redis dependency for api server  
  redis:
    image: redis:4.0-alpine
  
  # database dependency for api server
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: solo-platform
      POSTGRES_PASSWORD: solo-platform-db-password
      POSTGRES_DB: solo-platform

  # for viewing/debugging raw data in postgres
  adminer:
    image: adminer
    links:
      - postgres:postgres
    ports:
      - ${ADMINER_PORT}:8080
  
  # for viewing the api docs
  swaggerui:
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_PORT}:8080
    environment:
       API_URL: ${API_URL}

 # to enable gcloud login for pushing/pulling images from GCP
  gcp:
    image: google/cloud-sdk:178.0.0-alpine
    volumes:
      - gcp-data-volume:/root/.config
      - ./.gcp:/root/gcp
volumes:
  gcp-data-volume: {}
