source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'NewSolo' do
  node_modules_path = '../node_modules'

  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'RNOpenTok', path: "#{node_modules_path}/react-native-opentok/ios"
  pod 'BVLinearGradient', :path => "#{node_modules_path}/react-native-linear-gradient"
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end