source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'



target 'NewSolo' do
  node_modules_path = '../node_modules'

  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'BVLinearGradient', :path => "#{node_modules_path}/react-native-linear-gradient"
  pod 'RNDeviceInfo', :path => "#{node_modules_path}/react-native-device-info"
  pod 'react-native-camera', path: "#{node_modules_path}/react-native-camera"
  pod 'react-native-fetch-blob', :path => "#{node_modules_path}/react-native-fetch-blob" 
  pod 'React', :path => "#{node_modules_path}/react-native", :subspecs => [ 
     
    'RCTImage' 
] 
  pod 'react-native-image-resizer', :path => "#{node_modules_path}/react-native-image-resizer" 
  pod 'RNFS', :path => "#{node_modules_path}/react-native-fs" 
  pod 'RNI18n', :path => "#{node_modules_path}/react-native-i18n"
  pod 'react-native-keep-awake', :path => "#{node_modules_path}/react-native-keep-awake"
  pod 'react-native-background-timer', :path => "#{node_modules_path}/react-native-background-timer"
  pod 'ReactNativePermissions', :path => "#{node_modules_path}/react-native-permissions"
  pod 'Firebase/Messaging'

  pod 'RNSVG', :path => "#{node_modules_path}/react-native-svg"

  pod 'OpenTok'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

# Pods for AppCenter
  pod 'AppCenterReactNativeShared', '~> 1.5.1'
  

pod 'AppCenter/Analytics', '~> 1.6.1'
pod 'AppCenter/Crashes', '~> 1.6.1'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end